/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CreateOrganizationAdminsModel = require('../lib/Models/CreateOrganizationAdminsModel');
const TagModel = require('../lib/Models/TagModel');
const NetworkModel = require('../lib/Models/NetworkModel');
const UpdateOrganizationAdminModel = require('../lib/Models/UpdateOrganizationAdminModel');
const UpdateNetworkAlertSettingsModel = require('../lib/Models/UpdateNetworkAlertSettingsModel');
const DefaultDestinationsModel = require('../lib/Models/DefaultDestinationsModel');
const AlertModel = require('../lib/Models/AlertModel');
const UpdateNetworkBluetoothSettingsModel =
  require('../lib/Models/UpdateNetworkBluetoothSettingsModel');
const CreateOrganizationNetworksModel = require('../lib/Models/CreateOrganizationNetworksModel');
const UpdateNetworkModel = require('../lib/Models/UpdateNetworkModel');
const BindNetworkModel = require('../lib/Models/BindNetworkModel');
const UpdateNetworkSiteToSiteVpnModel = require('../lib/Models/UpdateNetworkSiteToSiteVpnModel');
const HubModel = require('../lib/Models/HubModel');
const SubnetModel = require('../lib/Models/SubnetModel');
const SnapshotNetworkCameraModel = require('../lib/Models/SnapshotNetworkCameraModel');
const ProvisionNetworkClientsModel = require('../lib/Models/ProvisionNetworkClientsModel');
const UpdateNetworkClientPolicyModel = require('../lib/Models/UpdateNetworkClientPolicyModel');
const UpdateNetworkClientSplashAuthorizationStatusModel =
  require('../lib/Models/UpdateNetworkClientSplashAuthorizationStatusModel');
const SsidsModel = require('../lib/Models/SsidsModel');
const UpdateNetworkDeviceModel = require('../lib/Models/UpdateNetworkDeviceModel');
const ClaimNetworkDevicesModel = require('../lib/Models/ClaimNetworkDevicesModel');
const BlinkLedsNetworkDeviceModel = require('../lib/Models/BlinkLedsNetworkDeviceModel');
const UpdateNetworkCellularFirewallRulesModel =
  require('../lib/Models/UpdateNetworkCellularFirewallRulesModel');
const RuleModel = require('../lib/Models/RuleModel');
const UpdateNetworkL3FirewallRulesModel =
  require('../lib/Models/UpdateNetworkL3FirewallRulesModel');
const UpdateNetworkL7FirewallRulesModel =
  require('../lib/Models/UpdateNetworkL7FirewallRulesModel');
const Rule2Model = require('../lib/Models/Rule2Model');
const UpdateOrganizationVpnFirewallRulesModel =
  require('../lib/Models/UpdateOrganizationVpnFirewallRulesModel');
const Rule3Model = require('../lib/Models/Rule3Model');
const UpdateNetworkSsidL3FirewallRulesModel =
  require('../lib/Models/UpdateNetworkSsidL3FirewallRulesModel');
const Rule4Model = require('../lib/Models/Rule4Model');
const CreateNetworkGroupPoliciesModel = require('../lib/Models/CreateNetworkGroupPoliciesModel');
const SchedulingModel = require('../lib/Models/SchedulingModel');
const MondayModel = require('../lib/Models/MondayModel');
const TuesdayModel = require('../lib/Models/TuesdayModel');
const WednesdayModel = require('../lib/Models/WednesdayModel');
const ThursdayModel = require('../lib/Models/ThursdayModel');
const FridayModel = require('../lib/Models/FridayModel');
const SaturdayModel = require('../lib/Models/SaturdayModel');
const SundayModel = require('../lib/Models/SundayModel');
const BandwidthModel = require('../lib/Models/BandwidthModel');
const BandwidthLimitsModel = require('../lib/Models/BandwidthLimitsModel');
const UpdateNetworkGroupPolicyModel = require('../lib/Models/UpdateNetworkGroupPolicyModel');
const CreateNetworkHttpServersModel = require('../lib/Models/CreateNetworkHttpServersModel');
const UpdateNetworkHttpServerModel = require('../lib/Models/UpdateNetworkHttpServerModel');
const CreateNetworkHttpServersWebhookTestsModel =
  require('../lib/Models/CreateNetworkHttpServersWebhookTestsModel');
const CreateOrganizationsModel = require('../lib/Models/CreateOrganizationsModel');
const UpdateOrganizationModel = require('../lib/Models/UpdateOrganizationModel');
const CloneOrganizationModel = require('../lib/Models/CloneOrganizationModel');
const UpdateOrganizationSnmpModel = require('../lib/Models/UpdateOrganizationSnmpModel');
const ClaimOrganizationModel = require('../lib/Models/ClaimOrganizationModel');
const UpdateOrganizationThirdPartyVPNPeersModel =
  require('../lib/Models/UpdateOrganizationThirdPartyVPNPeersModel');
const PeerModel = require('../lib/Models/PeerModel');
const IpsecPoliciesModel = require('../lib/Models/IpsecPoliciesModel');
const CreateNetworkPiiRequestsModel = require('../lib/Models/CreateNetworkPiiRequestsModel');
const CreateOrganizationSamlRolesModel = require('../lib/Models/CreateOrganizationSamlRolesModel');
const Tag2Model = require('../lib/Models/Tag2Model');
const Network2Model = require('../lib/Models/Network2Model');
const UpdateOrganizationSamlRoleModel = require('../lib/Models/UpdateOrganizationSamlRoleModel');
const UpdateNetworkSecurityMalwareSettingsModel =
  require('../lib/Models/UpdateNetworkSecurityMalwareSettingsModel');
const CreateNetworkSmTargetGroupsModel = require('../lib/Models/CreateNetworkSmTargetGroupsModel');
const UpdateNetworkSmTargetGroupModel = require('../lib/Models/UpdateNetworkSmTargetGroupModel');
const CreateNetworkSmProfileClarityModel =
  require('../lib/Models/CreateNetworkSmProfileClarityModel');
const UpdateNetworkSmProfileClarityModel =
  require('../lib/Models/UpdateNetworkSmProfileClarityModel');
const AddNetworkSmProfileClarityModel = require('../lib/Models/AddNetworkSmProfileClarityModel');
const CreateNetworkSmProfileUmbrellaModel =
  require('../lib/Models/CreateNetworkSmProfileUmbrellaModel');
const UpdateNetworkSmProfileUmbrellaModel =
  require('../lib/Models/UpdateNetworkSmProfileUmbrellaModel');
const AddNetworkSmProfileUmbrellaModel = require('../lib/Models/AddNetworkSmProfileUmbrellaModel');
const CreateNetworkSmAppPolarisModel = require('../lib/Models/CreateNetworkSmAppPolarisModel');
const UpdateNetworkSmAppPolariModel = require('../lib/Models/UpdateNetworkSmAppPolariModel');
const UpdateNetworkSmDevicesTagsModel = require('../lib/Models/UpdateNetworkSmDevicesTagsModel');
const UpdateNetworkSmDeviceFieldsModel = require('../lib/Models/UpdateNetworkSmDeviceFieldsModel');
const UpdateNetworkSmDevicesLockModel = require('../lib/Models/UpdateNetworkSmDevicesLockModel');
const UpdateNetworkSmDeviceWipeModel = require('../lib/Models/UpdateNetworkSmDeviceWipeModel');
const UpdateNetworkSmDevicesCheckinModel =
  require('../lib/Models/UpdateNetworkSmDevicesCheckinModel');
const UpdateNetworkSmDevicesMoveModel = require('../lib/Models/UpdateNetworkSmDevicesMoveModel');
const UpdateNetworkSsidsPlashSettingsModel =
  require('../lib/Models/UpdateNetworkSsidsPlashSettingsModel');
const UpdateNetworkSsidModel = require('../lib/Models/UpdateNetworkSsidModel');
const RadiusServerModel = require('../lib/Models/RadiusServerModel');
const RadiusAccountingServerModel = require('../lib/Models/RadiusAccountingServerModel');
const ApTagsAndVlanIdModel = require('../lib/Models/ApTagsAndVlanIdModel');
const UpdateNetworkSwitchSettingsModel = require('../lib/Models/UpdateNetworkSwitchSettingsModel');
const PowerExceptionModel = require('../lib/Models/PowerExceptionModel');
const UpdateDeviceSwitchPortModel = require('../lib/Models/UpdateDeviceSwitchPortModel');
const CreateNetworkSwitchStacksModel = require('../lib/Models/CreateNetworkSwitchStacksModel');
const AddNetworkSwitchStackModel = require('../lib/Models/AddNetworkSwitchStackModel');
const RemoveNetworkSwitchStackModel = require('../lib/Models/RemoveNetworkSwitchStackModel');
const UpdateNetworkSyslogServersModel = require('../lib/Models/UpdateNetworkSyslogServersModel');
const ServerModel = require('../lib/Models/ServerModel');
const UpdateNetworkContentFilteringModel =
  require('../lib/Models/UpdateNetworkContentFilteringModel');
const UpdateNetworkFirewalledServiceModel =
  require('../lib/Models/UpdateNetworkFirewalledServiceModel');
const UpdateNetworkOneToManyNatRulesModel =
  require('../lib/Models/UpdateNetworkOneToManyNatRulesModel');
const Rule5Model = require('../lib/Models/Rule5Model');
const UpdateNetworkOneToOneNatRulesModel =
  require('../lib/Models/UpdateNetworkOneToOneNatRulesModel');
const Rule6Model = require('../lib/Models/Rule6Model');
const UpdateNetworkPortForwardingRulesModel =
  require('../lib/Models/UpdateNetworkPortForwardingRulesModel');
const Rule7Model = require('../lib/Models/Rule7Model');
const CreateNetworkStaticRoutesModel = require('../lib/Models/CreateNetworkStaticRoutesModel');
const UpdateNetworkStaticRouteModel = require('../lib/Models/UpdateNetworkStaticRouteModel');
const UpdateNetworkUplinkSettingsModel = require('../lib/Models/UpdateNetworkUplinkSettingsModel');
const BandwidthLimits2Model = require('../lib/Models/BandwidthLimits2Model');
const CreateNetworkVlansModel = require('../lib/Models/CreateNetworkVlansModel');
const UpdateNetworkVlanModel = require('../lib/Models/UpdateNetworkVlanModel');
const ReservedIpRangeModel = require('../lib/Models/ReservedIpRangeModel');
const DhcpOptionModel = require('../lib/Models/DhcpOptionModel');
const UpdateNetworkVlansEnabledStateModel =
  require('../lib/Models/UpdateNetworkVlansEnabledStateModel');

const classMap = {
    CreateOrganizationAdminsModel,
    TagModel,
    NetworkModel,
    UpdateOrganizationAdminModel,
    UpdateNetworkAlertSettingsModel,
    DefaultDestinationsModel,
    AlertModel,
    UpdateNetworkBluetoothSettingsModel,
    CreateOrganizationNetworksModel,
    UpdateNetworkModel,
    BindNetworkModel,
    UpdateNetworkSiteToSiteVpnModel,
    HubModel,
    SubnetModel,
    SnapshotNetworkCameraModel,
    ProvisionNetworkClientsModel,
    UpdateNetworkClientPolicyModel,
    UpdateNetworkClientSplashAuthorizationStatusModel,
    SsidsModel,
    UpdateNetworkDeviceModel,
    ClaimNetworkDevicesModel,
    BlinkLedsNetworkDeviceModel,
    UpdateNetworkCellularFirewallRulesModel,
    RuleModel,
    UpdateNetworkL3FirewallRulesModel,
    UpdateNetworkL7FirewallRulesModel,
    Rule2Model,
    UpdateOrganizationVpnFirewallRulesModel,
    Rule3Model,
    UpdateNetworkSsidL3FirewallRulesModel,
    Rule4Model,
    CreateNetworkGroupPoliciesModel,
    SchedulingModel,
    MondayModel,
    TuesdayModel,
    WednesdayModel,
    ThursdayModel,
    FridayModel,
    SaturdayModel,
    SundayModel,
    BandwidthModel,
    BandwidthLimitsModel,
    UpdateNetworkGroupPolicyModel,
    CreateNetworkHttpServersModel,
    UpdateNetworkHttpServerModel,
    CreateNetworkHttpServersWebhookTestsModel,
    CreateOrganizationsModel,
    UpdateOrganizationModel,
    CloneOrganizationModel,
    UpdateOrganizationSnmpModel,
    ClaimOrganizationModel,
    UpdateOrganizationThirdPartyVPNPeersModel,
    PeerModel,
    IpsecPoliciesModel,
    CreateNetworkPiiRequestsModel,
    CreateOrganizationSamlRolesModel,
    Tag2Model,
    Network2Model,
    UpdateOrganizationSamlRoleModel,
    UpdateNetworkSecurityMalwareSettingsModel,
    CreateNetworkSmTargetGroupsModel,
    UpdateNetworkSmTargetGroupModel,
    CreateNetworkSmProfileClarityModel,
    UpdateNetworkSmProfileClarityModel,
    AddNetworkSmProfileClarityModel,
    CreateNetworkSmProfileUmbrellaModel,
    UpdateNetworkSmProfileUmbrellaModel,
    AddNetworkSmProfileUmbrellaModel,
    CreateNetworkSmAppPolarisModel,
    UpdateNetworkSmAppPolariModel,
    UpdateNetworkSmDevicesTagsModel,
    UpdateNetworkSmDeviceFieldsModel,
    UpdateNetworkSmDevicesLockModel,
    UpdateNetworkSmDeviceWipeModel,
    UpdateNetworkSmDevicesCheckinModel,
    UpdateNetworkSmDevicesMoveModel,
    UpdateNetworkSsidsPlashSettingsModel,
    UpdateNetworkSsidModel,
    RadiusServerModel,
    RadiusAccountingServerModel,
    ApTagsAndVlanIdModel,
    UpdateNetworkSwitchSettingsModel,
    PowerExceptionModel,
    UpdateDeviceSwitchPortModel,
    CreateNetworkSwitchStacksModel,
    AddNetworkSwitchStackModel,
    RemoveNetworkSwitchStackModel,
    UpdateNetworkSyslogServersModel,
    ServerModel,
    UpdateNetworkContentFilteringModel,
    UpdateNetworkFirewalledServiceModel,
    UpdateNetworkOneToManyNatRulesModel,
    Rule5Model,
    UpdateNetworkOneToOneNatRulesModel,
    Rule6Model,
    UpdateNetworkPortForwardingRulesModel,
    Rule7Model,
    CreateNetworkStaticRoutesModel,
    UpdateNetworkStaticRouteModel,
    UpdateNetworkUplinkSettingsModel,
    BandwidthLimits2Model,
    CreateNetworkVlansModel,
    UpdateNetworkVlanModel,
    ReservedIpRangeModel,
    DhcpOptionModel,
    UpdateNetworkVlansEnabledStateModel,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
